<?php
namespace SlimC;
/**
 * @author: Ali Kenan Yağmur
 * Date: 24.03.2016
 * Time: 23:22
 */
class SlimC extends \Slim\App {

    public function map(array $methods, $pattern, $callable)
    {
        if(is_string($callable)) {
            $callable = $this->setControllerMethod($callable);
        }

        return parent::map($methods, $pattern, $callable); // TODO: Change the autogenerated stub
    }

    public function setControllerMethod($callable)
    {
        list($controllerName,$controllerMethod) = explode('@',$callable);
        $controllerName = "App\\Controller\\".$controllerName;
        $callable = function () use ($controllerName,$controllerMethod) {
            $controller = new $controllerName();

            return call_user_func_array(array($controller,$controllerMethod),func_get_args());
        };

        return $callable;
    }
}